---
title: "code"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Import and modify Data

```{r}
library(tidyverse)
library(stringr)
# Omitting rows with NA, parsed date format
res <- read_csv(
  "restaurant_data.csv",
  col_types = cols(
    `INSPECTION DATE` = col_date(format = "%m / %d / %Y"),
    `GRADE DATE` = col_date(format = "%m / %d / %Y"),
    `RECORD DATE` = col_date(format = "%m / %d / %Y")
  )
) %>% na.omit(res) %>% filter(BORO != "Missing")
# replace names that are too long
res$`CUISINE DESCRIPTION` <-
  gsub(
    "Latin \\(Cuban, Dominican, Puerto Rican, South & Central American\\)",
    "Latin",
    res$`CUISINE DESCRIPTION`
  )

res$`CUISINE DESCRIPTION` <-
  gsub(
    "Bottled beverages, including water, sodas, juices, etc.",
    "Bottled beverages",
    res$`CUISINE DESCRIPTION`
  )

# Latest record for same restaurant
res_one <-
  arrange(res, desc(`GRADE DATE`)) %>% distinct(CAMIS, .keep_all = TRUE)
```

cleveland dot plot of cuisine type by borough

```{r}
# not omitting NAs, to include as much restaurants as possible

res_unique <- read_csv("restaurant_data.csv")[, 1:8] %>% distinct()%>% filter(BORO != "Missing")
res_unique$`CUISINE DESCRIPTION` <-
  gsub(
    "Latin \\(Cuban, Dominican, Puerto Rican, South & Central American\\)",
    "Latin",
    res_unique$`CUISINE DESCRIPTION`
  )

res_unique$`CUISINE DESCRIPTION` <-
  gsub(
    "Bottled beverages, including water, sodas, juices, etc.",
    "Bottled beverages",
    res_unique$`CUISINE DESCRIPTION`
  )

res_borough <- res_unique[,c(3,8)] 
res_borough$count <- rep(1,nrow(res_borough))
res_borough_t <- res_borough %>% group_by(`BORO`,`CUISINE DESCRIPTION`) %>% mutate(count=n()) %>% distinct()

ggplot(res_borough_t,aes(x=count,
                  y=fct_reorder2(`CUISINE DESCRIPTION`,BORO=="MANHATTAN",-count),
                  color=BORO)
                  )+  
  geom_point()+ylab("")
```

Exploring cuisine types and geolocations

```{r}
# Subsetting for restaurant near columbia
res_columbia <- filter(res_one,
                       res_one$ZIPCODE == 10025 |
                         res_one$ZIPCODE == 10026 |
                         res_one$ZIPCODE == 10027)
res_columbia_sum <-
  res_columbia %>% group_by(`CUISINE DESCRIPTION`) %>% summarize(total =
                                                                   n()) %>% arrange(desc(total))
# histogram
ggplot(res_columbia_sum) +
  geom_histogram(aes(x = reorder(`CUISINE DESCRIPTION`, total), y = total), stat = "identity") +
  coord_flip()
# cleveland dot plot
ggplot(res_columbia_sum) +
  geom_point(aes(x = reorder(`CUISINE DESCRIPTION`, total), y = total), stat = "identity") +
  coord_flip()
```
# word cloud
```{r}
# Chinese cuisine

library("wordcloud2")
library("wordcloud")

Chinese<- filter(res_one, res_one$`CUISINE DESCRIPTION` =="Chinese") %>% distinct(DBA) %>% toString() %>% str_remove_all(",") %>% str_remove_all("\"") %>% str_remove_all("\n")%>% str_remove_all("/")

word.freq.c <- table(strsplit(Chinese, " ")) %>% as.data.frame()
colnames(word.freq.c) <- c("Word","Freq")
wordcloud(word.freq.c$Word,word.freq.c$Freq)
wordcloud2(word.freq.c,minSize = 2)
# Japanese

Japanese<- filter(res_one, res_one$`CUISINE DESCRIPTION` =="Japanese") %>% distinct(DBA) %>% toString() %>% str_remove_all(",") %>% str_remove_all("\"") %>% str_remove_all("\n")%>% str_remove_all("/")

word.freq.j <- table(strsplit(Japanese, " ")) %>% as.data.frame()
colnames(word.freq.j) <- c("Word","Freq")
wordcloud(word.freq.j$Word,word.freq.j$Freq)
wordcloud2(word.freq.j,minSize = 2)
```
zipcode plots
```{r}

library(dplyr)
library(choroplethr)
library(devtools)
#install_github('arilamstein/choroplethrZip@v1.5.0')
library(choroplethrZip)
# NYC zipmap
res_zip <- res_one %>% group_by(ZIPCODE)%>% summarise(number=n())
colnames(res_zip) <- c("region","value")
res_zip$region <- as.character(res_zip$region)
nyc_fips <- c(36005, 36047, 36061, 36081, 36085)
zip_choropleth(res_zip,
                county_zoom = nyc_fips,
                title      = "Number of restaurants in New York",
                legend     = "count")

# Manhattan zipmap
res_man_zip <- res_one %>%filter(BORO=="MANHATTAN") %>%group_by(ZIPCODE)%>% summarise(number=n())
colnames(res_man_zip) <- c("region","value")
res_man_zip$region <- as.character(res_man_zip$region)

zip_choropleth(res_man_zip,
                county_zoom = 36061,
                title      = "Number of restaurants in Manhattan",
                legend     = "count")

# Manhattan Chinese zipmap
res_man_ch_zip <- res_one %>%filter(BORO=="MANHATTAN",`CUISINE DESCRIPTION`=="Chinese") %>%group_by(ZIPCODE)%>% summarise(number=n())
colnames(res_man_ch_zip) <- c("region","value")
res_man_ch_zip$region <- as.character(res_man_ch_zip$region)

zip_choropleth(res_man_ch_zip,
                county_zoom = 36061,
                title      = "Number of Chinese restaurants in Manhattan",
                legend     = "count")

               
```

analysis on violations

```{r}
# clean out the violations
res_viotype <- res %>% group_by(`VIOLATION DESCRIPTION`) %>% tally() %>% arrange(desc(n))
# rename to make them shorter
res_viotype[1:10,]$`VIOLATION DESCRIPTION` <- c("Non-food contact surface improperly constructed","Facility not vermin proof","Food contact surface not properly washed, rinsed and sanitized","Food not protected from potential source of contamination","Plumbing not properly installed or maintained","Evidence of mice or live mice present","Cold food item held above 41ºF","Hot food item not held at or above 140ºF","Filth flies or food/refuse/sewage-associated flies present","Food contact surface not properly maintained")
ggplot(top_n(res_viotype,10),aes(x=`VIOLATION DESCRIPTION`,y=n))+
  geom_bar(stat = "identity")+ coord_flip()+ggtitle("Top 10 violation reasons")

res_vioboro <- res%>% group_by(`VIOLATION CODE`,`BORO`) %>% tally() %>% arrange(desc(n)) %>% group_by(BORO) %>% top_n(5)

ggplot(res_vioboro,aes(x=`VIOLATION CODE`,y=n))+
  geom_bar(stat = "identity")+ 
  facet_wrap(~BORO,scales = "free")+
  ggtitle("Top 5 violation reasons for each borough")

cuisine.top15 <- res %>% group_by(`CUISINE DESCRIPTION`) %>% tally() %>% top_n(15)
top15.type <- cuisine.top15$`CUISINE DESCRIPTION` 
res_gcuisine <- res %>% filter(GRADE==c("A","B","C"))%>% filter(`CUISINE DESCRIPTION`==top15.type) %>% group_by(`CUISINE DESCRIPTION`,GRADE) %>% tally() 

ggplot(res_gcuisine,aes(x=`CUISINE DESCRIPTION`,y=n,fill=GRADE))+
  geom_bar(stat="identity",position = "fill")+coord_flip()+labs(y="Percentage",x="cuisine type")+ggtitle("Percentile of Grade for each cuisine type")
```

Grade A percentage in each area as zipmap

```{r}
res_gzip <- res_one %>% filter(GRADE==c("A","B","C"))%>%group_by(ZIPCODE,GRADE)%>% summarise(number=n())%>% group_by(ZIPCODE) %>% mutate(percent = 100*number/sum(number))

res_gazip <- filter(res_gzip,GRADE=="A")[,c(1,4)]
colnames(res_gazip) <- c("region","value")
res_gazip$region <- as.character(res_gazip$region)

res_gczip <- filter(res_gzip,GRADE=="C")[,c(1,4)]
colnames(res_gczip) <- c("region","value")
res_gczip$region <- as.character(res_gczip$region)

par(mfrow=c(1,2))
zip_choropleth(res_gazip,
                county_zoom = nyc_fips,
                title      = "Percent of Grade A restaurants in each zipcode area",
                legend     = "Percent")

zip_choropleth(res_gczip,
                county_zoom = nyc_fips,
                title      = "Percent of Grade C restaurants in each zipcode area",
                legend     = "Percent")

res_gzip_man <- res_one %>% filter(GRADE==c("A","B","C"))%>%filter(BORO=="MANHATTAN")%>%group_by(ZIPCODE,GRADE)%>% summarise(number=n())%>% group_by(ZIPCODE) %>% mutate(percent = 100*number/sum(number))

res_gazip_man <- filter(res_gzip_man,GRADE=="A")[,c(1,4)]
colnames(res_gazip_man) <- c("region","value")
res_gazip_man$region <- as.character(res_gazip_man$region)

res_gczip_man <- filter(res_gzip_man,GRADE=="C")[,c(1,4)]
colnames(res_gczip_man) <- c("region","value")
res_gczip_man$region <- as.character(res_gczip_man$region)

par(mfrow=c(2,1))
zip_choropleth(res_gazip_man,
                county_zoom = 36061,
                title      = "Percent of Grade A restaurants in Manhattan area",
                legend     = "Percent")

zip_choropleth(res_gczip_man,
                county_zoom = 36061,
                title      = "Percent of Grade C restaurants in Manhattan area",
                legend     = "Percent")
```